import { PUBLIC_MAX_PLAYERS, PUBLIC_MIN_PLAYERS } from '~/utils/env';

const DEFAULT_MAX_PLAYERS = 10;

const DEFAULT_MIN_PLAYERS = 2;

export const MAX_PLAYERS = Number(PUBLIC_MAX_PLAYERS) || DEFAULT_MAX_PLAYERS;
export const MIN_PLAYERS = Number(PUBLIC_MIN_PLAYERS) || DEFAULT_MIN_PLAYERS;

export const GAME_NAME = 'MY GAME';
