# This workflow will do a clean installation of node dependencies, cache/restore them, run linter and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on: pull_request

env:
  PUBLIC_SUPABASE_URL: ${{ vars.PUBLIC_SUPABASE_URL }}
  PUBLIC_SUPABASE_ANON_KEY: ${{ vars.PUBLIC_SUPABASE_ANON_KEY }}
  DEFAULT_USER_PASSWORD: ${{ secrets.DEFAULT_USER_PASSWORD }}
  HASH_SALT: ${{ secrets.HASH_SALT }}

jobs:
  checks:
    name: Run all checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'
      - run: npm ci
      - run: npm run check
      - run: npm run test:unit
      - run: npx playwright install --with-deps
      - run: npm run test
